USE master;
GO

CREATE DATABASE pizza;
GO

USE pizza;
GO

CREATE TABLE MENU(
pizza VARCHAR(25) NOT NULL,
price SMALLMONEY NOT NULL,
country VARCHAR(25),
base VARCHAR(25) NOT NULL,
CONSTRAINT MENU_PK PRIMARY KEY (pizza),
CONSTRAINT MENU_CK_BASE CHECK (base IN('white flour','wholemeal'))
);
GO

CREATE TABLE ITEMS (
ingredient VARCHAR(25) NOT NULL,
type VARCHAR(25) NOT NULL,
CONSTRAINT ITEMS_PK PRIMARY KEY (ingredient)
);
GO

CREATE TABLE RECIPE(
pizza VARCHAR(25) NOT NULL,
ingredient VARCHAR(25) NOT NULL,
amount SMALLINT NOT NULL,
CONSTRAINT RECIPE_PK PRIMARY KEY (pizza, ingredient),
CONSTRAINT MENURECIPE_FK FOREIGN KEY (pizza) REFERENCES MENU(pizza),
CONSTRAINT ITEMSRECIPE_FK FOREIGN KEY (ingredient) REFERENCES ITEMS(ingredient)
);
GO


